from io import BytesIO
from datetime import datetime

from reportlab.lib.pagesizes import letter
from reportlab.pdfgen import canvas


def generate_manual_issue_pdf(
    *,
    material_code: str,
    material_name: str,
    location_code: str,
    lot: str,
    qty: float,
    uom: str,
    notes: str,
    issued_by: str,
    issued_at: datetime | None = None,
) -> BytesIO:
    """
    Returns a BytesIO buffer containing a one-page PDF.
    """
    issued_at = issued_at or datetime.now()

    buf = BytesIO()
    c = canvas.Canvas(buf, pagesize=letter)
    width, height = letter

    # Header
    c.setFont("Helvetica-Bold", 16)
    c.drawString(50, height - 60, "AWLMIX HOUSTON")
    c.setFont("Helvetica", 12)
    c.drawString(50, height - 85, "Manual Issue Record")

    c.setFont("Helvetica", 10)
    c.drawString(50, height - 110, f"Issued At: {issued_at.strftime('%Y-%m-%d %H:%M:%S')}")
    c.drawString(300, height - 110, f"Issued By: {issued_by}")

    # Body box layout
    y = height - 150
    line_h = 18

    def row(label: str, value: str):
        nonlocal y
        c.setFont("Helvetica-Bold", 10)
        c.drawString(50, y, label)
        c.setFont("Helvetica", 10)
        c.drawString(170, y, value)
        y -= line_h

    row("Material Code:", material_code)
    row("Material Name:", material_name)
    row("Location:", location_code)
    row("Lot / Batch #:", lot or "(blank)")
    row("Quantity Issued:", f"{qty:,.4f} {uom}")

    y -= 8
    c.setFont("Helvetica-Bold", 10)
    c.drawString(50, y, "Notes:")
    y -= line_h

    c.setFont("Helvetica", 10)
    notes_text = notes.strip() or "(blank)"
    # basic wrap
    max_chars = 95
    for i in range(0, len(notes_text), max_chars):
        c.drawString(70, y, notes_text[i : i + max_chars])
        y -= line_h

    # Footer
    c.setFont("Helvetica", 8)
    c.drawString(50, 40, "Generated by AWLMIX Inventory App (Streamlit)")

    c.showPage()
    c.save()
    buf.seek(0)
    return buf
