from io import BytesIO
from datetime import datetime

from reportlab.lib.pagesizes import letter
from reportlab.lib import colors
from reportlab.platypus import SimpleDocTemplate, Table, TableStyle, Paragraph, Spacer
from reportlab.lib.styles import getSampleStyleSheet

str(ln.get("Notes", "") or header_notes),


def generate_multi_issue_pdf(
    *,
    lines: list[dict],
    issued_by: str,
    header_notes: str = "",
    issued_at: datetime | None = None,
) -> BytesIO:
    """
    ONE PDF with a table of multiple issued materials.

    Each line dict should contain:
      MaterialCode, MaterialName, LocationCode, Lot, Qty, UOM, Notes
    """
    issued_at = issued_at or datetime.now()
    buf = BytesIO()

    doc = SimpleDocTemplate(buf, pagesize=letter, leftMargin=36, rightMargin=36, topMargin=36, bottomMargin=36)
    styles = getSampleStyleSheet()

    story = []
    story.append(Paragraph("<b>AWLMIX HOUSTON</b>", styles["Title"]))
    story.append(Paragraph("Manual Issue Record (Multiple Materials)", styles["Heading2"]))
    story.append(Spacer(1, 8))

    story.append(Paragraph(f"<b>Issued At:</b> {issued_at.strftime('%Y-%m-%d %H:%M:%S')}", styles["Normal"]))
    story.append(Paragraph(f"<b>Issued By:</b> {issued_by or 'Unknown'}", styles["Normal"]))
    if header_notes.strip():
        story.append(Paragraph(f"<b>Header Notes:</b> {header_notes.strip()}", styles["Normal"]))
    story.append(Spacer(1, 12))

    data = [["MaterialCode", "MaterialName", "Location", "Lot", "Qty", "UOM", "Notes"]]
    for ln in lines:
        data.append([
            str(ln.get("MaterialCode", "")),
            str(ln.get("MaterialName", "")),
            str(ln.get("LocationCode", "")),
            str(ln.get("Lot", "")),
            f"{float(ln.get('Qty', 0.0)):.4f}",
            str(ln.get("UOM", "")),
            str(ln.get("Notes", "")),
        ])

    table = Table(data, repeatRows=1, colWidths=[85, 150, 65, 70, 55, 40, 115])
    table.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, 0), colors.lightgrey),
        ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
        ("FONTSIZE", (0, 0), (-1, 0), 9),
        ("FONTSIZE", (0, 1), (-1, -1), 8),
        ("GRID", (0, 0), (-1, -1), 0.5, colors.grey),
        ("VALIGN", (0, 0), (-1, -1), "TOP"),
        ("ROWBACKGROUNDS", (0, 1), (-1, -1), [colors.white, colors.whitesmoke]),
        ("LEFTPADDING", (0, 0), (-1, -1), 4),
        ("RIGHTPADDING", (0, 0), (-1, -1), 4),
        ("TOPPADDING", (0, 0), (-1, -1), 3),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 3),
    ]))

    story.append(table)
    story.append(Spacer(1, 12))
    story.append(Paragraph("Generated by AWLMIX Inventory App (Streamlit)", styles["Normal"]))

    doc.build(story)
    buf.seek(0)
    return buf

